### ISSUE TITLE
Live Audio?

### ISSUE THREAD

**Issue by ItsRogueRen** [Pegorari/tagarela#3]
Is it possible to use this to animate a model in real-time as audio is sent from a mic input? If so this may be something HUGE for what I'm working on!

**Comment by Pegorari** [comment]
Hello, it's not possible. But I stopped to maintain this project anyway.
You can find some solutions on asset store.

Em ter, 1 de dez de 2020 12:36, Rogue Ren <notifications@github.com>
escreveu:

**Comment by ItsRogueRen** [comment]
Unfortunately I can't use anything in the asset store as I'm building for Linux. Sad that this won't work.
